{% set version = "0.3.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggpmisc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggpmisc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggpmisc/ggpmisc_{{ version }}.tar.gz
  sha256: 5ab10b6309ea68f54a6ec5d9e434bbd819fb5a92510c780514eb216a3c93aad4

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mass >=7.3_51.4
    - r-broom >=0.5.2
    - r-dplyr >=0.8.3
    - r-ggplot2 >=3.2.1
    - r-gridextra >=2.3
    - r-lubridate >=1.7.4
    - r-magrittr >=1.5
    - r-plyr >=1.8.4
    - r-polynom >=1.4_0
    - r-rlang >=0.4.0
    - r-scales >=1.0.0
    - r-splus2r >=1.2_2
    - r-stringr >=1.4.0
    - r-tibble >=2.1.3
    - r-xts >=0.11_2
    - r-zoo >=1.8_6
  run:
    - r-base
    - r-mass >=7.3_51.4
    - r-broom >=0.5.2
    - r-dplyr >=0.8.3
    - r-ggplot2 >=3.2.1
    - r-gridextra >=2.3
    - r-lubridate >=1.7.4
    - r-magrittr >=1.5
    - r-plyr >=1.8.4
    - r-polynom >=1.4_0
    - r-rlang >=0.4.0
    - r-scales >=1.0.0
    - r-splus2r >=1.2_2
    - r-stringr >=1.4.0
    - r-tibble >=2.1.3
    - r-xts >=0.11_2
    - r-zoo >=1.8_6

test:
  commands:
    - $R -e "library('ggpmisc')"           # [not win]
    - "\"%R%\" -e \"library('ggpmisc')\""  # [win]

about:
  home: https://www.r4photobiology.info, https://bitbucket.org/aphalo/ggpmisc
  license: GPL-2
  summary: 'Extensions to ''ggplot2'' respecting the grammar of graphics paradigm. Specialization
    of method ggplot(): accept and convert on the fly time series data. Geom: "table",
    "plot" and "grob" add insets to plots using native data coordinates, while "table_npc",
    "plot_npc" and "grob_npc" do the same using "npc" coordinates through new aesthetics
    "npcx" and "npcy". Statistics: locate and tag peaks and valleys; count observations
    in different quadrants of a plot; select observations based on 2D density; label
    with the equation of a polynomial fitted with lm() or other types of models; labels
    with P-value, R^2 or adjusted R^2 or information criteria for fitted models; label
    with ANOVA table for fitted models; label with summary for fitted models. Model
    fit classes for which suitable methods are provided by package ''broom'' are supported.
    Scales and stats to build volcano and quadrant plots based on outcomes, fold changes,
    p-values and false discovery rates.'
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ggpmisc
# Type: Package
# Title: Miscellaneous Extensions to 'ggplot2'
# Version: 0.3.2
# Date: 2019-11-11
# Authors@R: c( person("Pedro J.", "Aphalo", email = "pedro.aphalo@helsinki.fi", role = c("aut", "cre"), comment = c(ORCID = "0000-0003-3385-972X")), person("Kamil", "Slowikowski", role = "ctb") )
# Maintainer: Pedro J. Aphalo <pedro.aphalo@helsinki.fi>
# Description: Extensions to 'ggplot2' respecting the grammar of graphics paradigm. Specialization of method ggplot(): accept and convert on the fly time series data. Geom: "table", "plot" and "grob" add insets to plots using native data coordinates, while "table_npc", "plot_npc" and "grob_npc" do the same using "npc" coordinates through new aesthetics "npcx" and "npcy". Statistics: locate and tag peaks and valleys; count observations in different quadrants of a plot; select observations based on 2D density; label with the equation of a polynomial fitted with lm() or other types of models; labels with P-value, R^2 or adjusted R^2 or information criteria for fitted models; label with ANOVA table for fitted models; label with summary for fitted models. Model fit classes for which suitable methods are provided by package 'broom' are supported. Scales and stats to build volcano and quadrant plots based on outcomes, fold changes, p-values and false discovery rates.
# License: GPL (>= 2)
# LazyData: TRUE
# LazyLoad: TRUE
# ByteCompile: TRUE
# Depends: R (>= 3.5.0), ggplot2 (>= 3.2.1)
# Imports: grid, rlang (>= 0.4.0), magrittr (>= 1.5), gridExtra (>= 2.3), scales (>= 1.0.0), MASS (>= 7.3-51.4), polynom (>= 1.4-0), splus2R (>= 1.2-2), tibble (>= 2.1.3), plyr (>= 1.8.4), dplyr (>= 0.8.3), xts (>= 0.11-2), zoo (>= 1.8-6), broom (>= 0.5.2), lubridate (>= 1.7.4), stringr (>= 1.4.0)
# Suggests: knitr (>= 1.25), rmarkdown (>= 1.15), nlme (>= 3.1-140), gginnards(>= 0.0.2), ggrepel (>= 0.8.1), magick (>= 2.2)
# URL: https://www.r4photobiology.info, https://bitbucket.org/aphalo/ggpmisc
# BugReports: https://bitbucket.org/aphalo/ggpmisc/issues
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-11-11 13:53:21 UTC; aphalo
# Author: Pedro J. Aphalo [aut, cre] (<https://orcid.org/0000-0003-3385-972X>), Kamil Slowikowski [ctb]
# Repository: CRAN
# Date/Publication: 2019-11-11 14:50:02 UTC
