{% set version = '0.3.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggpmisc
  version: {{ version|replace("-", "_") }}

source:
  fn: ggpmisc_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ggpmisc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggpmisc/ggpmisc_{{ version }}.tar.gz
  sha256: 9f2d4cc58e4d7509880201cd05021419130d68107166463bcde7c8b4f0f8b8d6

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mass >=7.3_50
    - r-broom >=0.4.4
    - r-dplyr >=0.7.6
    - r-ggplot2 >=3.0.0
    - r-gridextra >=2.3
    - r-lubridate >=1.7.4
    - r-magrittr >=1.5
    - r-plyr >=1.8.4
    - r-polynom >=1.3_9
    - r-rlang >=0.2.1
    - r-splus2r >=1.2_2
    - r-tibble >=1.4.2
    - r-xts >=0.10_2
    - r-zoo >=1.8_1
  run:
    - r-base
    - r-mass >=7.3_50
    - r-broom >=0.4.4
    - r-dplyr >=0.7.6
    - r-ggplot2 >=3.0.0
    - r-gridextra >=2.3
    - r-lubridate >=1.7.4
    - r-magrittr >=1.5
    - r-plyr >=1.8.4
    - r-polynom >=1.3_9
    - r-rlang >=0.2.1
    - r-splus2r >=1.2_2
    - r-tibble >=1.4.2
    - r-xts >=0.10_2
    - r-zoo >=1.8_1

test:
  commands:
    - $R -e "library('ggpmisc')"           # [not win]
    - "\"%R%\" -e \"library('ggpmisc')\""  # [win]

about:
  home: https://www.r4photobiology.info, https://bitbucket.org/aphalo/ggpmisc
  license: GPL (>= 2)
  summary: 'Extensions to ''ggplot2'' respecting the grammar of graphics paradigm. Specialization
    of method ggplot(): accept and convert on the fly  time series data. Geom: "table",
    adds tables to plots. Statistics: locate  and tag peaks and valleys in 2D plots;
    count observations in different  quadrants of a plot; select observations based
    on 2D density; label with the  equation of a polynomial fitted with lm() or other
    types of models; labels  with P-value, R^2 or adjusted R^2 or information criteria
    for fitted models;  label with ANOVA table for fitted models; label with summary
    for fitted  models. Model fit classes for which suitable methods are provided by
    package ''broom'' are supported.'
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
