travis:
  secure:
    BINSTAR_TOKEN: zInRaZ8cW90wL3tKMv+/BlRVQA2k4/10809nNiBPMOZbaoFuikDhLXCluOuX9H7kWU5e2q8NHlv2+Jj8THzoL3WWsKjhzOVIMm+jE3o6DzxYc752mB8fcP5qqZWz4oLCoGx1RtrAhi8Oo/zoI08vFweEEcj8CGDcp7hXOlNWW0eF2Li/yd5n2ZG0Ue4PlQpj2qU5ZpVR8yN3TsNjf8mhg9BUbV975BHLqYKeHEUaMNMj5P4A7fr3OnQ7ZO/iQeOFmF849JNBkZl2ZfDJm8H4t2FDNsRswOgptyM30Xcyvf6azx9FLCHRL7kTMwHwavjpu5Y6xIyEgtjdsF3KTWX8A9kkkeAMqLiydOF3i3TT6uON6QnujGdDj9f36O8i4GVDTnpCg6lmZgtvPkOs+3VXC7B6yVVLNLquisCs+ptiOli040nL8XzJZX+aXbI0aAquk/s6yIvX5dMqLtjlONDznxViRJKFufRjLBUGVVtg1uqgcPfNvEDci9wRgFMT7lDIK2l3ILwmbIDb6WEImSn0JIEs4JP4IUWWCAdrDhrmiEgdMQjZn90dIEL0fyX9JhPC/5Nh/LlS495Ps05HSreM4Hm7FudsaelrxcsOiMfDO0Sc8cbu+IiarnWxw3ojlMji1fApg+PgvWsO0tb6NUCaVNWpv46Sjah6gI6anV7wc4A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
